### ISSUE TITLE
Publishing Bundle on Composer

### ISSUE THREAD

**Issue by pagbrl** [OPENVIEW-DEV/FpdmBundle#1]
Hi,

I really like your bundle, do you plan on publishing it on composer so it becomes easier to deploy it on multiple installations ? 

Thanks !

**Comment by nicoladarold** [comment]
Hi,
in order to add the bundle in composer we should do a refactor work and should add tests and a decent manual. We have not the resources  for this, as we switched to TCPDF and this bundle is no more used by our company.
We decided to leave this bundle to the comunity, if of any use, so feel free to fork it and use as base for a better package.
